### ISSUE TITLE
验证码可不可以去掉或者使用谷歌的，我好像没找到在哪里配置

### ISSUE THREAD

**Issue by yukaidi1220** [2331892928/AMEN-GoEdge-User_backEnd#4]

**Comment by 2331892928** [comment]
可以关闭，但不能去掉。但关闭后，仍有些是打开的(这是必选项为了安全) 忘了哪些 好像有发送验证码之类的

**Comment by yukaidi1220** [comment]
请求 URL: http://www.yukaidi.top/api/UserService/registerUser
请求方法: POST
状态代码: 500 Internal Server Error
  File "/www/wwwroot/x/Controller/UserService.py", line 92, in registerUser
    res = GoEdge_Api.createUser(username, password, mobile, email, username, ip, None, mobile, api['nodeClusterId'])
                                          ^^^^^^^^
NameError: name 'password' is not defined

**Comment by 2331892928** [comment]
<img width="636" alt="image" src="https://github.com/2331892928/AMEN-GoEdge-User_backEnd/assets/69388528/28e874c3-70bb-4738-87ad-7b4affcb3638">
password 不可能没有定义，你是否修改了代码？

**Comment by 2331892928** [comment]
如果你有问题，我可以帮你搭建。提供你的联系方式

**Comment by ning0818** [comment]
> 如果你有问题，我可以帮你搭建。提供你的联系方式

能帮帮我不？qq2191155607
