### ISSUE TITLE
大佬视频打不开了

### ISSUE THREAD

**Issue by ning0818** [2331892928/AMEN-GoEdge-User_backEnd#7]
![Screenshot_20240614_224755_com huawei browser](https://github.com/2331892928/AMEN-GoEdge-User_backEnd/assets/117955401/cc5ebc63-345f-49d1-b1cc-4404ada4fd93)

**Comment by 2331892928** [comment]
官方onedrive-vercel-index项目错误或微软公司错误 等待恢复

**Comment by 2331892928** [comment]
已成功修复
